### ISSUE TITLE
Ввод CAPTCHA при авторизации

### ISSUE THREAD

**Issue by avkochekov** [feschukov/rhythmbox-plugin-yandex-music#25]
(10:43:33) [0x55e3be8d4390] [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:204: Не удалось получить токен
(10:43:33) [0x55e3be8d4390] [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:205: {'error': '403', 'error_description': 'CAPTCHA required', 'x_captcha_key': '00A1YZyr78RDuW7CMSwjOF8G2QAxNBWQ', 'x_captcha_url': 'https://ext.captcha.yandex.net/image?key=00A1YZyr78RDuW7CMSwjOF8G2QAxNBWQ'}

**Comment by dobroweb** [comment]
Добрый день. Проблема известная. К сожалению, пока я не работал в этом направлении, чтобы CAPTCHA обрабатывать. Постараюсь в ближайшее время решить этот вопрос.

**Comment by dobroweb** [comment]
Добрый день. Проблема известная. К сожалению, пока обработку CAPTCHA я ещё не делал. Постараюсь в ближайшее время заняться этим вопросом.

**Comment by feschukov** [comment]
@avkochekov прошу проверить функционал ввода CAPTCHA при авторизации https://github.com/feschukov/rhythmbox-plugin-yandex-music/commit/d03640645392e6f20b32edf407c9470f437958f9

**Comment by avkochekov** [comment]
@feschukov к сожалению не знаком с питоном, так бы подключился к отладке плагина.
Увы, авторизоваться не удалось. Получаю следующий вывод:
{'error': 'invalid_grant', 'error_description': 'login or password is not valid'}
При авторизации пробовал различные комбинации:

    логин - формата xy.zzzzzzz и [xy.zzzzzzz@yandex.ru](mailto:xy.zzzzzzz@yandex.ru)
    пароль - и от аккаунта, и "пароль приложения"

**Comment by feschukov** [comment]
> @feschukov, увы, авторизоваться не удалось. Но с капчей вроде все ок. Получаю следующий вывод: `{'error': 'invalid_grant', 'error_description': 'login or password is not valid'}` При авторизации пробовал различные комбинации:
> 
> * логин - формата xy.zzzzzzz и xy.zzzzzzz(at)yandex.ru (не может ли здесь быть проблемы???)
> * пароль - и от аккаунта, и "пароль приложения"
> 
> к сожалению не знаком с питоном, так бы подключился к отладке плагина.

Вот я тоже с этим столкнулся при проверке функционала. Но это скорее всего уже в [тему авторизации #3](https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/3) надо писать
