### ISSUE TITLE
авторизация с одноразовым паролем?

### ISSUE THREAD

**Issue by tst32** [feschukov/rhythmbox-plugin-yandex-music#3]
так нельзя, если включена двухфакторная в Яше?

**Comment by dobroweb** [comment]
Не тестировал авторизацию при включенной двухфакторке. У меня она отключена и я авторизовался основным паролем, так как одноразовый не подошел для генерации токена. С авторизацией в целом есть сложности, особенно для новых аккаунтов, а также для аккаунтов с включенной двухфакторной авторизацией.

В используемой python библиотеке yandex-music-api есть обсуждение авторизации https://github.com/MarshalX/yandex-music-api/discussions/439
Автор библиотеки в марте 2021 года говорил о том, что сейчас Яндекс переезжает на новую систему авторизации. Но судя по issues https://github.com/MarshalX/yandex-music-api/issues/414 работа над внедрением новой системы авторизации ещё не завершена. Как только будет стабильный релиз библиотеки 2.0.0, я вернусь к решению данного вопроса.

**Comment by dobroweb** [comment]
> Может быть, стоит имплементировать авторизацию по уникальным паролям приложений?

Невозможно. Для этого Яндекс официально должен открыть API сервиса Яндекс.Музыка.

**Comment by darkhex** [comment]
При включенной двухфакторной аутентификации все работает по одноразовому паролю (используя Я ключ). Если создавать пароль для приложения для музыки, допустим, то не работает.

**Comment by ohot2015** [comment]
у меня через двухфакторку тоже без проблем

**Comment by dobroweb** [comment]
Наверное, заработало после обновления способа авторизации https://github.com/dobroweb/rhythmbox-plugin-yandex-music/pull/4

**Comment by cka304huk-m** [comment]
Если авторизация пароль+смс не работает. Работает только через пароль.
Делал пароль для приложения, не пускает в учетку:
![изображение](https://user-images.githubusercontent.com/50353911/167710169-04da6da7-9984-45d7-b235-fc5a530b6dee.png)

**Comment by feschukov** [comment]
Предложили новую систему авторизации https://github.com/feschukov/rhythmbox-plugin-yandex-music/commit/feec4965b2e3526b21de158ce369fc08deafa56e. Я её принял, так как старая перестала работать. Теперь придётся ручками из строки браузера дергать код авторизации, но зато должен работать абсолютно любой вариант авторизации: без 2FA, с ней, по одноразовому коду, QR и так далее. Потому как для авторизации используется родной интерфейс Яндекс. Если у кого-то ещё остались проблемы с авторизацией, прошу проверить.

**Comment by Infinity10K** [comment]
не работает вход по одноразовому коду
```(23:48:18) <rhythmbox> [YandexMusic.do_activate] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:31: Yandex.Music plugin activating
(23:48:52) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:232: Не удалось получить токен
(23:48:52) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:233: {'error': 'invalid_grant', 'error_description': 'login or password is not valid'}
(23:49:27) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:232: Не удалось получить токен
(23:49:27) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:233: {'error': 'invalid_grant', 'error_description': 'login or password is not valid'}
```

P.S. переключил в настройках акка яндекса на обычный пароль, аналогично не даёт войти

**Comment by feschukov** [comment]
Более не актуально. Используется новая система авторизации
