### ISSUE TITLE
Яндекс музыка не появилась в плагине

### ISSUE THREAD

**Issue by pobornic** [feschukov/rhythmbox-plugin-yandex-music#31]
`rhythmbox -D yandex-music`
вывод:

> _(rhythmbox:18980): Gtk-WARNING **: 12:25:00.288: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)
> 
> (rhythmbox:18980): Gtk-WARNING **: 12:25:00.288: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)
> /usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2736: instance '0x56357489b360' has no handler with id '14062'
>   return func(*args, **kwargs)_

![rhythmdox_yandex-music](https://user-images.githubusercontent.com/39998941/196143168-f3e27a6a-717b-46ae-baf9-1fe9c5502159.png)

**Comment by feschukov** [comment]
Добрый день. Могли бы полный вывод дать из терминала? Потому что в данном выводе ничего непонятно и упоминания плагина нет.

Была такая проблема у пользователя после обновления на Ubuntu 22.04 https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/29. Вероятнее всего у вас регается на отсутствие библиотеки yandex_music, это самая распространённая ошибка.

**Comment by pobornic** [comment]
> Добрый день. Могли бы полный вывод дать из терминала? Потому что в данном выводе ничего непонятно и упоминания плагина нет.
> 
> Была такая проблема у пользователя после обновления на Ubuntu 22.04 #29. Вероятнее всего у вас регается на отсутствие библиотеки yandex_music, это самая распространённая ошибка.

srgv@srgv-desktop:~/Downloads/temp_music_plugin$ rhythmbox -D yandex-music

> (rhythmbox:20986): Gtk-WARNING **: 12:53:30.246: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)
> 
> (rhythmbox:20986): Gtk-WARNING **: 12:53:30.246: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)
> /usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2736: instance '0x55a236835d60' has no handler with id '14318'
>   return func(*args, **kwargs)
> /usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2736: instance '0x55a236835d60' has no handler with id '14317'
>   return func(*args, **kwargs)
> 
> (rhythmbox:20986): Gtk-WARNING **: 12:53:47.499: Can't set a parent on widget which has a parent
> 
Rhythmbox 3.4.4

**Comment by pobornic** [comment]
> Добрый день. Могли бы полный вывод дать из терминала? Потому что в данном выводе ничего непонятно и упоминания плагина нет.
> 
> Была такая проблема у пользователя после обновления на Ubuntu 22.04 #29. Вероятнее всего у вас регается на отсутствие библиотеки yandex_music, это самая распространённая ошибка.

да действительно причина была в том, что я не выполнил `pip install yandex-music --upgrade`
