### ISSUE TITLE
Ошибка КАПЧИ.

### ISSUE THREAD

**Issue by mrutsy** [feschukov/rhythmbox-plugin-yandex-music#35]
При вводе логина и пароля, выводит ошибку капчи. Соответственно, никакой капчи он не отображает.

(18:43:20) <rhythmbox> [YandexMusic.do_activate] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:31: Yandex.Music plugin activating
(18:43:37) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:232: Не удалось получить токен
(18:43:37) <rhythmbox> [YandexMusic.generate_token] .local/share/rhythmbox/plugins/yandex-music/yandex-music.py:233: {'error': '403', 'error_description': 'CAPTCHA required', 'x_captcha_key': '00AGykxz0xfEJ7W5kL0aQTJwL8ZeZ0bE', 'x_captcha_url': 'https://ext.captcha.yandex.net/image?key=00AGykxz0xfEJ7W5kL0aQTJwL8ZeZ0bE'}

**Comment by feschukov** [comment]
Доброе утро. В курсе этой проблемы. Нашёл описание того, как надо правильно с капчей работать https://github.com/MarshalX/yandex-music-api/issues/140. Напишу окно ввода капчи и его обработку.

**Comment by feschukov** [comment]
Закрываю в связи с тем, что дубль https://github.com/feschukov/rhythmbox-plugin-yandex-music/issues/25
