### ISSUE TITLE
login or password is not valid

### ISSUE THREAD

**Issue by kellmorok** [feschukov/rhythmbox-plugin-yandex-music#41]
После активации плагина, сразу же запрашивается логин/пароль и открывается несколько наложенных друг на друга окон авторизации.
При попытке авторизоваться ошибка login or password is not valid. Двухфакторка отключена, пароль точно верный.
ОС Ubuntu 23.04
_Извиняюсь за скрин вместо листинга, всё делается на планшете, копипаст проблемный)_
![изображение_2023-02-10_101243775](https://user-images.githubusercontent.com/92925648/218006339-ac20e408-5981-4326-8468-c1319f7c1f2d.png)

**Comment by feschukov** [comment]
Добрый день. Авторизация по логину и паролю больше не работает. Установите тестовую версию плагина, там новая схема авторизации. Я обновлю релизную версию в ближайшее время.

**Comment by kellmorok** [comment]
День добрый. Спасибо!

**Comment by kellmorok** [comment]
при попытке установить тестовый плагин ошибка:
`kellmorok@kellmorok-Hi10-X:~/.local/share/rhythmbox/plugins$ git clone git@github.com:feschukov/rhythmbox-plugin-yandex-music.git ~/.local/share/rhythmbox/plugins/yandex-music
Клонирование в «/home/kellmorok/.local/share/rhythmbox/plugins/yandex-music»...
git@github.com: Permission denied (publickey).
fatal: Не удалось прочитать из внешнего репозитория.

Удостоверьтесь, что у вас есть необходимые права доступа
и репозиторий существует.
`

**Comment by feschukov** [comment]
Попробуйте установить этой командой
```
git clone https://github.com/feschukov/rhythmbox-plugin-yandex-music.git ~/.local/share/rhythmbox/plugins/yandex-music
```

**Comment by kellmorok** [comment]
Правильно ли я понимаю, что нужно вставить токен после code&client_id? С ним тоже проблема с авторизацией
