### ISSUE TITLE
Rhythmbox: не удалось установить плагин по инструкции. Яндекс Музыки нет во вкладке слева

### ISSUE THREAD

**Issue by SergeyLiseev** [feschukov/rhythmbox-plugin-yandex-music#42]
.......~$ rhythmbox -D yandex-music

(rhythmbox:5445): Gtk-WARNING **: 11:54:58.594: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type b, target type NULL)

(rhythmbox:5445): Gtk-WARNING **: 11:54:58.594: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type b, target type NULL)
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:493: Warning: ../../../gobject/gsignal.c:2765: instance '0x561d1c1c2e80' has no handler with id '14475'
  return func(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:493: Warning: ../../../gobject/gsignal.c:2765: instance '0x561d1c1c2e80' has no handler with id '14474'
  return func(*args, **kwargs)

(rhythmbox:5445): Gtk-WARNING **: 11:55:42.558: Can't set a parent on widget which has a parent

**Comment by kellmorok** [comment]
pip install yandex-music --upgrade
mkdir -p ~/.local/share/rhythmbox/plugins/
git clone https://github.com/feschukov/rhythmbox-plugin-yandex-music.git ~/.local/share/rhythmbox/plugins/yandex-music

**Comment by feschukov** [comment]
Я немного не понял, при установке плагина у вас не возникло проблем? Если удалить плагин, то ошибка из указанного выше лога пропадает?

**Comment by SergeyLiseev** [comment]
Прошу прощения, протупил ))
Не обратил внимания на это: "необходимо его активировать в настройках Rhythmbox"
Заработало, спасибо!
